### ISSUE TITLE
Import sequences bug

### ISSUE THREAD

**Issue by rsanchezgarc** [I2PC/scipion-em-xmipp#137]
If no sequence name is provided, analyze results crashes

Exception in Tkinter callback
Traceback (most recent call last):
  File "/mnt/gauss/data/rsanchez/app/scipion/software/lib/python2.7/lib-tk/Tkinter.py", line 1541, in __call__
    return self.func(*args)
  File "/mnt/gauss/data/rsanchez/app/scipion/pyworkflow/gui/project/viewprotocols.py", line 1984, in _analyzeResultsClicked
    self._analyzeResults(prot)
  File "/mnt/gauss/data/rsanchez/app/scipion/pyworkflow/gui/project/viewprotocols.py", line 1978, in _analyzeResults
    protocol=prot)
  File "/mnt/gauss/data/rsanchez/app/scipion/pyworkflow/em/viewers/viewer_sequence.py", line 65, in visualize
    self.protocol._getTmpPath(seqName + ".fasta"))
TypeError: unsupported operand type(s) for +: 'NoneType' and 'str'

**Comment by DStrelak** [comment]
@rsanchezgarc what's the status?

**Comment by rsanchezgarc** [comment]
No idea. You probably need to ask @mmmtnez

**Comment by DaniDelHoyo** [comment]
I was walking around the issues and I found this long forgotten one. The problem was actually in scipion-em, not in xmipp, but I fixed it a while ago and it is already available in devel branch, so I am closing this issue.
Cheers
