### ISSUE TITLE
test xmipp3.tests.test_protocols_xmipp_mics fails

### ISSUE THREAD

**Issue by rmarabini** [I2PC/scipion-em-xmipp#22]
>>>>> python  /home/marta/software/scipion_plugin/pyworkflow/apps/pw_protocol_run.py "/home/marta/ScipionUserData/projects/TestXmippVarianceFiltering" "Runs/000154_XmippProtParticlePicking/logs/run.db" "154"
[   FAILED ] TestXmippVarianceFiltering.setUpClass

Traceback (most recent call last):
  File "/home/marta/software/scipion_plugin/software/lib/python2.7/unittest/suite.py", line 146, in _handleClassSetUp
    setUpClass()
  File "/home/marta/software/scipion_plugin/software/lib/python2.7/site-packages/xmipp3/tests/test_protocols_xmipp_mics.py", line 623, in setUpClass
    cls.protPP = cls.runFakedPicking(cls.protDown.outputMicrographs, cls.allCrdsDir)
  File "/home/marta/software/scipion_plugin/software/lib/python2.7/site-packages/xmipp3/tests/test_protocols_xmipp_mics.py", line 112, in runFakedPicking
    if cls.protPP.outputCoordinates is None:
AttributeError: 'XmippProtParticlePicking' object has no attribute 'outputCoordinates'

**Comment by dmaluenda** [comment]
It's not failing in Buildbot, now.

**Comment by dmaluenda** [comment]
I will close this. Feel free to re-open if some issue.
