### ISSUE TITLE
optical_alignment related test does not work (at least with CPU)

### ISSUE THREAD

**Issue by rmarabini** [I2PC/scipion-em-xmipp#23]
[   FAILED ] TestOFAlignment.testAlignOF1

Traceback (most recent call last):
  File "/home/marta/software/scipion_plugin/software/lib/python2.7/unittest/case.py", line 329, in run
    testMethod()
  File "/home/marta/software/scipion_plugin/software/lib/python2.7/site-packages/xmipp3/tests/test_protocols_xmipp_movies.py", line 120, in testAlignOF1
    label="Movie MRC")
  File "/home/marta/software/scipion_plugin/software/lib/python2.7/site-packages/xmipp3/tests/test_protocols_xmipp_movies.py", line 115, in runOFProtocol
    self.launchProtocol(protOF)
  File "/home/marta/software/scipion_plugin/pyworkflow/tests/tests.py", line 107, in launchProtocol
    raise Exception("ERROR launching protocol.")
Exception: ERROR launching protocol.

**Comment by dmaluenda** [comment]
They are failing due to opencv is not installed on nolan

**Comment by dmaluenda** [comment]
They are failing due to opencv is not installed on nolan

**Comment by dmaluenda** [comment]
I tried to install opencv on nolan but without success....

**Comment by dmaluenda** [comment]
This have fixed in https://github.com/I2PC/xmipp/pull/43 and in buildbot here: http://arquimedes.cnb.csic.es:9980/#/builders/52/builds/5 -> steps 68 and 69.

I'm closing this.
