### ISSUE TITLE
TestSubProj.test_pattern fails

### ISSUE THREAD

**Issue by rmarabini** [I2PC/scipion-em-xmipp#24]
xmipp substract protocol fails when no CTF is used

>>>>> python  /home/marta/software/scipion_plugin/pyworkflow/apps/pw_protocol_run.py "/home/marta/ScipionUserData/projects/TestSubProj" "Runs/000437_ProtRelionSubtract/logs/run.db" "437"
[   FAILED ] TestSubProj.test_pattern

Traceback (most recent call last):
  File "/home/marta/software/scipion_plugin/software/lib/python2.7/unittest/case.py", line 329, in run
    testMethod()
  File "/home/marta/software/scipion_plugin/software/lib/python2.7/site-packages/xmipp3/tests/test_protocols_subtract_projection.py", line 571, in test_pattern
    self.assertIsNotNone(protSubtract.outputParticles, "There was a problem with subtract projection")
AttributeError: 'XmippProtSubtractProjection' object has no attribute 'outputParticles'

**Comment by dmaluenda** [comment]
In buildbot is running well. It is failing there if relion is not installed.

**Comment by dmaluenda** [comment]
Test is passing in buildbod: http://arquimedes.cnb.csic.es:9980/#/builders/52/builds/5 -> step 75.

I'm clossing this.
