### ISSUE TITLE
ctf consensus fails to filter ctf set

### ISSUE THREAD

**Issue by azazellochg** [I2PC/scipion-em-xmipp#267]
Running without consensus fails
```
00010:   Traceback (most recent call last):
00011:     File "/lmb/home/gsharov/soft/scipion3/scipion-pyworkflow/pyworkflow/protocol/protocol.py", line 188, in run
00012:       self._run()
00013:     File "/lmb/home/gsharov/soft/scipion3/scipion-pyworkflow/pyworkflow/protocol/protocol.py", line 1311, in _run
00014:       self._insertAllSteps()  # Define steps for execute later
00015:     File "/public/EM/Scipion/miniconda3/envs/.scipion3env/lib/python3.8/site-packages/xmipp3/protocols/protocol_ctf_consensus.py", line 191, in _insertAllSteps
00016:       self.ctfFn2 = self.inputCTF2.get().getFileName()
00017:   AttributeError: 'NoneType' object has no attribute 'getFileName'
00018:   ------------------- PROTOCOL FAILED (DONE 0/0)
```

**Comment by azazellochg** [comment]
Looks fixed
