### ISSUE TITLE
ModuleNotFoundError: No module named 'pyvista'

### ISSUE THREAD

**Issue by mmmtnez** [I2PC/scipion-em-xmipp#331]
When I try to run the next test: 

scipion3 tests xmipp3.tests.test_protocol_extract_asymmetric_unit

I have the next error:

Scipion v3.0.5 () devel
Running tests....
[   FAILED ] _FailedTest.test_protocol_extract_asymmetric_unit

Traceback (most recent call last):
  File "/usr/lib/python3.6/unittest/case.py", line 59, in testPartExecutor
    yield
  File "/usr/lib/python3.6/unittest/case.py", line 605, in run
    testMethod()
  File "/usr/lib/python3.6/unittest/loader.py", line 34, in testFailure
    raise self._exception
ImportError: Failed to import test module: test_protocol_extract_asymmetric_unit
Traceback (most recent call last):
  File "/usr/lib/python3.6/unittest/loader.py", line 153, in loadTestsFromName
    module = __import__(module_name)
  File "/home/marta/software/scipion3/xmipp-bundle/src/scipion-em-xmipp/xmipp3/tests/test_protocol_extract_asymmetric_unit.py", line 45, in <module>
    from xmipp3.protocols import XmippProtExtractUnit
  File "/home/marta/software/scipion3/xmipp-bundle/src/scipion-em-xmipp/xmipp3/protocols/__init__.py", line 66, in <module>
    from .protocol_movie_gain import XmippProtMovieGain
  File "/home/marta/software/scipion3/xmipp-bundle/src/scipion-em-xmipp/xmipp3/protocols/protocol_movie_gain.py", line 46, in <module>
    from xmipp3.utils import normalize_array
  File "/home/marta/software/scipion3/xmipp-bundle/src/scipion-em-xmipp/xmipp3/utils.py", line 33, in <module>
    import pyvista as pv
ModuleNotFoundError: No module named 'pyvista'

**Comment by DStrelak** [comment]
Hi @mmmtnez,
This will be fixed promptly. See 
https://github.com/I2PC/scipion-em-xmipp/pull/329

**Comment by DStrelak** [comment]
Fixed
