### ISSUE TITLE
MonoRes fails if maxRes is empty

### ISSUE THREAD

**Issue by mmmtnez** [I2PC/scipion-em-xmipp#337]
MonoRes step2 (resolutionMonogenicSignalStep) fails if maxRes param is empty, even though the right side help says that "If Low is empty MonoRes will try to estimate the range. it should be better if a range is provided".

Params selected: Volume Half1 & Volume Half2 (No mask, no Low Resolution Range, rest by default).
Error:

STARTED: resolutionMonogenicSignalStep, step 2
Traceback (most recent call last):
File "/home/roberto/scipion3/scipion3/lib/python3.7/site-packages/pyworkflow/protocol/protocol.py", line 187, in run
self._run()
File "/home/roberto/scipion3/scipion3/lib/python3.7/site-packages/pyworkflow/protocol/protocol.py", line 238, in _run
resultFiles = self._runFunc()
File "/home/roberto/scipion3/scipion3/lib/python3.7/site-packages/pyworkflow/protocol/protocol.py", line 234, in _runFunc
return self._func(*self._args)
File "/home/roberto/scipion3/scipion3/lib/python3.7/site-packages/xmipp3/protocols/protocol_resolution_monogenic_signal.py", line 266, in resolutionMonogenicSignalStep
params +='-maxRes %f % self.maxRes.get()
TypeError: must be real number, not NoneType
Protocol failed: must be real number, not NoneType

**Comment by DStrelak** [comment]
@Vilax what's the status?

**Comment by Vilax** [comment]
I will fix it this week :)
