### ISSUE TITLE
DeepEMhancer analyze results broken

### ISSUE THREAD

**Issue by rsanchezgarc** [I2PC/scipion-em-xmipp#343]
Hi, the analyze results button is raising a complain about a non existent axis_output.bild file. Since I have no idea how the viewer works, I would need help fixing it.

Traceback (most recent call last):
  File "/home/ruben/app/anaconda3/envs/.scipion3env/lib/python3.8/tkinter/__init__.py", line 1883, in __call__
    return self.func(*args)
  File "/home/ruben/app/anaconda3/envs/.scipion3env/lib/python3.8/site-packages/pyworkflow/gui/project/viewprotocols.py", line 2146, in _analyzeResultsClicked
    self._analyzeResults(prot)
  File "/home/ruben/app/anaconda3/envs/.scipion3env/lib/python3.8/site-packages/pyworkflow/gui/project/viewprotocols.py", line 2121, in _analyzeResults
    firstViewer.visualize(prot)
  File "/home/ruben/app/anaconda3/envs/.scipion3env/lib/python3.8/site-packages/pyworkflow/viewer.py", line 144, in visualize
    for view in self._visualize(obj, **kwargs):
  File "/home/ruben/app/xmipp_bundle/src/scipion-em-xmipp/xmipp3/viewers/viewer_deepEMHancer.py", line 85, in _visualize
    Chimera.createCoordinateAxisFile(dim,
  File "/home/ruben/app/anaconda3/envs/.scipion3env/lib/python3.8/site-packages/pwem/viewers/viewer_chimera.py", line 126, in createCoordinateAxisFile
    ff = open(bildFileName, "w")
FileNotFoundError: [Errno 2] No such file or directory: 'Runs/000210_XmippProtDeepVolPostProc/tmp/axis_output.bild'

**Comment by dmaluenda** [comment]
I don't really know. A couple of sources comes to my mind.

1) from the ChimerX refactorization.

2) from the usage of a scratch disk for the tmp folder.

@mmmtnez knows more than me about 1, and @pconesa the same for the 2.

**Comment by pconesa** [comment]
Yes, this look like a consequence of not having to folder available after a protocol finished. A quick fix is to us extra folder instead

**Comment by rsanchezgarc** [comment]
It seems the bug also affects localdeblur

**Comment by Vilax** [comment]
What's the state of this issue? It seems solved

**Comment by pconesa** [comment]
The chimera viewer is been fixed a long time ago and is released.
Now, what I do not know is if the viewer is making the right call here:

`File "/home/ruben/app/xmipp_bundle/src/scipion-em-xmipp/xmipp3/viewers/viewer_deepEMHancer.py", line 85, in _visualize
Chimera.createCoordinateAxisFile(dim,`

And if so, if that change is been released.
