### ISSUE TITLE
fsc-q

### ISSUE THREAD

**Issue by gregdp** [I2PC/scipion-em-xmipp#429]
I get the following when trying to run FSC-Q:

Traceback (most recent call last):
  File "/home/parallels/conda/envs/scipion3/lib/python3.8/site-packages/pyworkflow/gui/form.py", line 2250, in _close
    message = self.callback(self.protocol, onlySave, doSchedule)
  File "/home/parallels/conda/envs/scipion3/lib/python3.8/site-packages/pyworkflow/gui/project/viewprotocols.py", line 1951, in _executeSaveProtocol
    self._updateSelection()
  File "/home/parallels/conda/envs/scipion3/lib/python3.8/site-packages/pyworkflow/gui/project/viewprotocols.py", line 1581, in _updateSelection
    self._fillSummary()
  File "/home/parallels/conda/envs/scipion3/lib/python3.8/site-packages/pyworkflow/gui/project/viewprotocols.py", line 1836, in _fillSummary
    self.summaryText.setReadOnly(False)
  File "/home/parallels/conda/envs/scipion3/lib/python3.8/site-packages/pyworkflow/gui/text.py", line 286, in setReadOnly
    self.config(state=state)
  File "/home/parallels/conda/envs/scipion3/lib/python3.8/tkinter/__init__.py", line 1646, in configure
    return self._configure('configure', cnf, kw)
  File "/home/parallels/conda/envs/scipion3/lib/python3.8/tkinter/__init__.py", line 1636, in _configure
    self.tk.call(_flatten((self._w, cmd)) + self._options(cnf))
_tkinter.TclError: invalid command name ".!toplevel.!frame.!frame2.!protocolsview.!panedwindow.!frame2.!panedwindow.!frame2.!notebook.!frame.!frame2.!taggedtext"

**Comment by DStrelak** [comment]
Hi @gregdp ,

Thanks for reporting this issue.
Can you elaborate on what you did before you saw this issue?
Did you open existing project or did this error occur with newly added protocol?
Did you change any fields in the protocol? If yes, can you share a screenshot of it?
What is your Scipion version and version of the Scipion-em-xmipp plugin?

@JorMaister, can I ask you to keep an eye on this issue in case it's Scipion related?

**Comment by JorMaister** [comment]
Sure, @DStrelak.
@gregdp, could you please provide the execution details requested by @DStrelak? We can reproduce your issue that way and fix it asap.

**Comment by gregdp** [comment]
It may have been related to a file permission issue, I moved my project files and it works ok now. Thanks!
