### ISSUE TITLE
Bug center particles protocol

### ISSUE THREAD

**Issue by rsanchezgarc** [I2PC/scipion-em-xmipp#574]
Hi, I got the following error when I used the center particles protocol with a subset of classes (which means that the class names are not consecutive). It is in the createOutputStep

I have attached the files
[007044_XmippProtCenterParticles.tar.gz](https://github.com/I2PC/scipion-em-xmipp/files/9794163/007044_XmippProtCenterParticles.tar.gz)

```
00033:   Traceback (most recent call last):
00034:     File "/home/sanchezg/app/miniconda3/envs/scipion3/lib/python3.8/site-packages/pyworkflow/protocol/protocol.py", line 202, in run
00035:       self._run()
00036:     File "/home/sanchezg/app/miniconda3/envs/scipion3/lib/python3.8/site-packages/pyworkflow/protocol/protocol.py", line 253, in _run
00037:       resultFiles = self._runFunc()
00038:     File "/home/sanchezg/app/miniconda3/envs/scipion3/lib/python3.8/site-packages/pyworkflow/protocol/protocol.py", line 249, in _runFunc
00039:       return self._func(*self._args)
00040:     File "/home/sanchezg/app/miniconda3/envs/scipion3/lib/python3.8/site-packages/xmipp3/protocols/protocol_center_particles.py", line 179, in createOutputStep
00041:       self._fillClasses(outputClasses)
00042:     File "/home/sanchezg/app/miniconda3/envs/scipion3/lib/python3.8/site-packages/xmipp3/protocols/protocol_center_particles.py", line 225, in _fillClasses
00043:       newClass.append(part)
00044:     File "/home/sanchezg/app/miniconda3/envs/scipion3/lib/python3.8/site-packages/pwem/objects/data.py", line 1160, in append
00045:       EMSet.append(self, image)
00046:     File "/home/sanchezg/app/miniconda3/envs/scipion3/lib/python3.8/site-packages/pyworkflow/object.py", line 1245, in append
00047:       self._insertItem(item)
00048:     File "/home/sanchezg/app/miniconda3/envs/scipion3/lib/python3.8/site-packages/pyworkflow/object.py", line 1249, in _insertItem
00049:       self._getMapper().insert(item)
00050:     File "/home/sanchezg/app/miniconda3/envs/scipion3/lib/python3.8/site-packages/pyworkflow/mapper/sqlite.py", line 772, in insert
00051:       self.db.insertObject(obj.getObjId(), obj.isEnabled(), obj.getObjLabel(), obj.getObjComment(),
00052:     File "/home/sanchezg/app/miniconda3/envs/scipion3/lib/python3.8/site-packages/pyworkflow/mapper/sqlite.py", line 1247, in insertObject
00053:       self.executeCommand(self.INSERT_OBJECT, args)
00054:   sqlite3.IntegrityError: UNIQUE constraint failed: Class001_Objects.id
00055:   Protocol failed: UNIQUE constraint failed: Class001_Objects.id
```

**Comment by danielmarchan3** [comment]
Hi @rsanchezgarc , I tried to replicate the same error building the same centeredStack.xmd with a substet of classes in the input and testing a bunch of different situations and it seems that the bug has been be corrected by some PR done in this past year. I will close this issue but if you encountered the error again, please create a new issue. 
Thanks for your help!
