### ISSUE TITLE
case.py AssertionError: False is not true : Downsampling failed

### ISSUE THREAD

**Issue by ugepac** [I2PC/scipion-em-xmipp#698]
When testing Scipion3 on Ubuntu 22.04 with the command scipion3 tests xmipp3.tests.test_protocols_xmipp_mics.TestXmippPreprocessMicrographs the following error is generated, which seems to be related to the five lines of code in the case.py file in miniconda.

[ FAILED ] TestXmippPreprocessMicrographs.testDownsampling

Traceback (most recent call last):
  File "/home/prove/miniconda/envs/scipion3/lib/python3.8/unittest/case.py", line 60, in testPartExecutor
    yield
  File '/home/provs/miniconda/envs/scipion3/lib/python3.8/unittest/case.py', line 676, in run
    self._callTestMethod(testMethod)
  File "/home/test/miniconda/envs/scipion3/lib/python3.8/unittest/case.py", line 633, in _callTestMethod
    method()
  File "/home/prove/miniconda/envs/scipion3/lib/python3.8/site-packages/xmipp3/tests/test_protocols_xmipp_mics.py", line 196, in testDownsampling
    self.assertTrue(protDown.isFinished(), 'Downsampling failed')
  File "/home/test/miniconda/envs/scipion3/lib/python3.8/unittest/case.py", line 765, in assertTrue
    raise self.failureException(msg)
AssertionError: False is not true : Downsampling failed

Out of five tests, one fails while the other four pass.

Imported mics: 5, processed mics: 0
Imported mics: 5, processed mics: 1
Imported mics: 5, processed mics: 3
Imported mics: 5, processed mics: 5
[ RUN OK ] TestXmippPreprocessMicrographs.testStreaming (40.221 secs)

[==========] run 5 tests (74.006 secs)

[FAILED ] 1 test

[PASSED ] 4 tests

Can you solve this problem?

![Schermata del 2023-06-16 15-05-17](https://github.com/I2PC/scipion-em-xmipp/assets/136808601/8ff3cdbb-e5d8-490f-9a8b-c6461b84fe37)

**Comment by albertmena** [comment]
Fixed on devel, thanks for the information
