### ISSUE TITLE
error in cl2d viewer

### ISSUE THREAD

**Issue by azazellochg** [I2PC/scipion-em-xmipp#75]
When I click to display classes or cores or stable cores I get:
```
Exception in Tkinter callback
Traceback (most recent call last):
  File "/lmb/home/gsharov/soft/scipion2/software/lib/python2.7/lib-tk/Tkinter.py", line 1541, in __call__
    return self.func(*args)
  File "/lmb/home/gsharov/soft/scipion2/pyworkflow/gui/form.py", line 1207, in _visualizeVar
    self.visualizeCallback(self.paramName)
  File "/lmb/home/gsharov/soft/scipion2/pyworkflow/viewer.py", line 314, in _visualizeParam
    views = self._getVisualizeDict()[paramName](paramName)
  File "/lmb/home/gsharov/soft/xmipp_bundle/src/scipion-em-xmipp/xmipp3/viewers/viewer_cl2d.py", line 143, in _viewLevelFiles
    views.append(em.ClassesView(self.getProject(),
AttributeError: 'module' object has no attribute 'ClassesView'
```

**Comment by dmaluenda** [comment]
Thanks @azazellochg. It was fixed in fec8136ceee3fc7c9b9d73bf9034978105bda0d1 , so update your version.

I will close this. Feel free to re-open if needed.
